version: "3.8"
services:
  nuxt-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tech2work-app
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - PORT=3000
      - HOST=0.0.0.0
